Update Place Validations Functionality.yml

diff --git a/.github/workflows/Place Validations Functionality.yml b/.github/workflows/Place Validations Functionality.yml
--- a/.github/workflows/Place Validations Functionality.yml
+++ b/.github/workflows/Place Validations Functionality.yml
@@ -29,8 +29,8 @@ jobs:
         distribution: 'temurin'
         cache: maven
 
-    -  name:  List of the directiories
-       run:  ls -R    /home/runner/work/autdemo/autdemo/test-output     
+    -  name: check of the directiories
+       run:  ls -R    /home/runner/work/autdemo/autdemo/test-output || echo "file not found"  
       
 
     -  name: Download previous report
