Update Place Validations Functionality.yml

diff --git a/.github/workflows/Place Validations Functionality.yml b/.github/workflows/Place Validations Functionality.yml
--- a/.github/workflows/Place Validations Functionality.yml
+++ b/.github/workflows/Place Validations Functionality.yml
@@ -30,7 +30,7 @@ jobs:
         cache: maven
 
     -  name: check of the directiories
-       run:  ls -R    /home/runner/work/autdemo/autdemo/test-output || echo "file not found"  
+       run:  ls -R    /home/runner/work/autdemo/autdemo/target || echo "file not found"  
       
 
     -  name: Download previous report
